export declare const habitCheckbox: string;
export declare const habitRow: string;
export declare const habitRowSurface: string;
export declare const habitRowSurfaceCompleted: string;
export declare const rowBody: string;
export declare const rowMeta: string;
export declare const rowTitle: string;
export declare const streakBadge: string;
export declare const visuallyHidden: string;
