import type { CreateBookmarkPayload } from "@/db/types/bookmark";
import type { Bookmark } from "@/db/types/bookmark";
import type { BookmarkCategory, CreateBookmarkCategoryPayload } from "@/db/types/bookmarkCategory";
import type { Habit } from "@/db/types/habit";
import type { AppSettings, TextColorKey, ThemeMode } from "@/db/types/settings";
import type { CreateTodoPayload, TodoItem } from "@/db/types/todo";
import type { WeatherCache } from "@/db/types/weather";
import type { Workspace } from "@/db/types/workspace";

export interface HomePageProps {
  timeLabel: string;
  dateLabel: string;
  theme: ThemeMode;
  settings: AppSettings;
  weather: WeatherCache | null;
  workspaces: Workspace[];
  activeWorkspaceId: string | null;
  todos: TodoItem[];
  habits: Habit[];
  bookmarks: Bookmark[];
  bookmarkCategories: BookmarkCategory[];
  noteText: string;
  onThemeToggle: (theme: ThemeMode) => Promise<void>;
  onActiveSearchEngineChange: (engineId: string) => Promise<void>;
  onTimeFormatChange: (value: AppSettings["timeFormat"]) => Promise<void>;
  onTimezoneChange: (value: string) => Promise<void>;
  onLocaleChange: (value: AppSettings["locale"]) => Promise<void>;
  onDateFormatChange: (value: AppSettings["dateFormat"]) => Promise<void>;
  onTabTitleChange: (value: string) => Promise<void>;
  onBackgroundImageChange: (file: File) => Promise<void>;
  onBackgroundImageRemove: () => Promise<void>;
  onTextColorChange: (key: TextColorKey, value: string | null) => Promise<void>;
  onTextColorsReset: () => Promise<void>;
  onAddCustomSearchEngine: (payload: { name: string; urlTemplate: string }) => Promise<void>;
  onRemoveCustomSearchEngine: (engineId: string) => Promise<void>;
  onWeatherCityChange: (city: string) => Promise<void>;
  onRefreshWeather: () => Promise<void>;
  onSelectWorkspace: (id: string) => Promise<void>;
  onAddWorkspace: (name: string) => Promise<void>;
  onDeleteWorkspace: (id: string) => Promise<void>;
  onAddTodo: (payload: CreateTodoPayload) => Promise<void>;
  onToggleTodo: (todoId: string) => Promise<void>;
  onDeleteTodo: (todoId: string) => Promise<void>;
  onReorderTodo: (orderedIds: string[]) => Promise<void>;
  onAddHabit: (title: string) => Promise<void>;
  onToggleHabitToday: (habitId: string) => Promise<void>;
  onDeleteHabit: (habitId: string) => Promise<void>;
  onAddBookmark: (payload: CreateBookmarkPayload) => Promise<void>;
  onDeleteBookmark: (bookmarkId: string) => Promise<void>;
  onAddBookmarkCategory: (payload: CreateBookmarkCategoryPayload) => Promise<void>;
  onDeleteBookmarkCategory: (categoryId: string) => Promise<void>;
  onSaveNote: (text: string) => Promise<void>;
}
