export declare const compactButton: string;
export declare const modalActions: string;
export declare const modalBody: string;
export declare const modalCard: string;
export declare const modalCardLg: string;
export declare const modalCardMd: string;
export declare const modalCardSm: string;
export declare const modalHeader: string;
export declare const modalOverlay: string;
